name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs: 
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install prerequisites ubuntu
      if: ${{ matrix.platform }} == 'ubuntu-latest'
      shell: bash
      run: |
        sudo apt update
        sudo apt-get install libusb-1.0-0-dev

    - name: Install prerequisites macos
      if: ${{ matrix.platform }} == 'macos-latest'
      shell: bash
      run: |
        brew update
        brew install libusb

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest
