name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  install_packages_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        shell: bash
        run: |
          sudo apt update
          sudo apt-get install libusb-1.0-0-dev

  install_packages_macos:
    runs-on: macos-latest

    steps:
      - name: Install prerequisites
        shell: bash
        run: |
          brew update
          brew install libusb

  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest
