name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs: 
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.7", "3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install prerequisites
      if: ${{ matrix.platform }} == 'ubuntu-latest'
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt-get install libusb-1.0-0-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew update
          brew install libusb
        elif [ "$RUNNER_OS" == "Windows" ]; then
          echo "$RUNNER_OS no need to install prerequisites"
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Build and install
      run: pip install --verbose .[test]

    - name: Test
      run: python -m pytest
